// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Ehtp8uwTxcpOje_D5MBPMy_ZoUMHz1s',
    appId: '1:15877777638:web:f8b8de5a7e9c3e8efc3327',
    messagingSenderId: '15877777638',
    projectId: 'event-booking-44324',
    authDomain: 'event-booking-44324.firebaseapp.com',
    storageBucket: 'event-booking-44324.firebasestorage.app',
    measurementId: 'G-8NRZ6X04NT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8061IXWEvTGpc2LP2Ws26WHWNdCqi1AI',
    appId: '1:15877777638:android:5f1e7b3f0ca0a498fc3327',
    messagingSenderId: '15877777638',
    projectId: 'event-booking-44324',
    storageBucket: 'event-booking-44324.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP4u3VCLgTMqWPgGBc6WBSyZdRo-PBlW0',
    appId: '1:15877777638:ios:d4a2242ee8c150bdfc3327',
    messagingSenderId: '15877777638',
    projectId: 'event-booking-44324',
    storageBucket: 'event-booking-44324.firebasestorage.app',
    iosBundleId: 'com.example.eventBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP4u3VCLgTMqWPgGBc6WBSyZdRo-PBlW0',
    appId: '1:15877777638:ios:d4a2242ee8c150bdfc3327',
    messagingSenderId: '15877777638',
    projectId: 'event-booking-44324',
    storageBucket: 'event-booking-44324.firebasestorage.app',
    iosBundleId: 'com.example.eventBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7Ehtp8uwTxcpOje_D5MBPMy_ZoUMHz1s',
    appId: '1:15877777638:web:4a20d2c531dd708ffc3327',
    messagingSenderId: '15877777638',
    projectId: 'event-booking-44324',
    authDomain: 'event-booking-44324.firebaseapp.com',
    storageBucket: 'event-booking-44324.firebasestorage.app',
    measurementId: 'G-YM70TY196M',
  );
}
